export const DISPLAY_ALERT = 'SHOW_ALERT'

export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR= 'SETUP_USER_ERROR'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_RENTAL_BEGIN = 'CREATE_RENTAL_BEGIN'
export const CREATE_RENTAL_SUCCESS = 'CREATE_RENTAL_SUCCESS'
export const CREATE_RENTAL_ERROR = 'CREATE_RENTAL_ERROR'

export const GET_ALLRENTALS_BEGIN = 'GET_ALLRENTALS_BEGIN'
export const GET_ALLRENTALS_SUCCESS = 'GET_ALLRENTALS_SUCCESS'

export const GET_RENTALBYID_BEGIN = 'GET_RENTALBYIDL_BEGIN'
export const GET_RENTALBYID_SUCCESS = 'GET_RENTALBYID_SUCCESS'
export const GET_RENTALBYID_ERROR = 'GET_RENTALBYID_ERROR'

export const SET_ACTIVE_ACTION = 'SET_ACTIVE_ACTION'
export const SET_ACTIVE_ACTION_SUCCESS = 'SET_ACTIVE_ACTION_SUCCESS'

export const CREATE_ACTION_BEGIN = 'CREATE_ACTION_BEGIN'
export const CREATE_ACTION_SUCCESS = 'CREATE_ACTION_SUCCESS'
export const CREATE_ACTION_ERROR = 'CREATE_ACTION_ERROR'

export const DELETE_ACTION_BEGIN = 'DELETE_ACTION_BEGIN'

export const SET_EDIT_ACTION = 'SET_EDIT_ACTION'

export const EDIT_ACTION_BEGIN = 'EDIT_ACTION_BEGIN'
export const EDIT_ACTION_SUCCESS = 'EDIT_ACTION_SUCCESS'
export const EDIT_ACTION_ERROR = 'EDIT_ACTION_ERROR'

export const CREATE_NOTE_BEGIN = 'CREATE_NOTE_BEGIN'
export const CREATE_NOTE_SUCCESS = 'CREATE_NOTE_SUCCESS'
export const CREATE_NOTE_ERROR = 'CREATE_NOTE_ERROR'
