export const DISPLAY_ALERT = 'SHOW_ALERT'

export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR= 'SETUP_USER_ERROR'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const GET_USERS_BEGIN = 'GET_USERS_BEGIN'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_ERROR = 'GET_USERS_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_OWNER_BEGIN = 'CREATE_OWNER_BEGIN'
export const CREATE_OWNER_SUCCESS = 'CREATE_OWNER_SUCCESS'
export const CREATE_OWNER_ERROR = 'CREATE_OWNER_ERROR'

export const GET_OWNERS_BEGIN = 'GET_OWNERS_BEGIN'
export const GET_OWNERS_SUCCESS = 'GET_OWNERS_SUCCESS'

export const SET_ACTIVE_OWNER = 'SET_ACTIVE_OWNER' 
export const SET_ACTIVE_OWNER_SUCCESS = 'SET_ACTIVE_OWNER_SUCCESS'

export const SET_EDIT_OWNER = 'SET_EDIT_OWNER'

export const EDIT_OWNER_BEGIN = 'EDIT_OWNER_BEGIN'
export const EDIT_OWNER_SUCCESS = 'EDIT_OWNER_SUCCESS'
export const EDIT_OWNER_ERROR = 'EDIT_OWNER_ERROR'

export const DELETE_OWNER_BEGIN = 'DELETE_OWNER_BEGIN'

export const GET_RENTALBYOWNER_BEGIN = 'GET_RENTALBYOWNER_BEGIN'
export const GET_RENTALBYOWNER_SUCCESS = 'GET_RENTALBYOWNER_SUCCESS'
export const GET_RENTALBYOWNER_ERROR = 'GET_RENTALBYOWNER_ERROR'

export const CREATE_RENTAL_BEGIN = 'CREATE_RENTAL_BEGIN'
export const CREATE_RENTAL_SUCCESS = 'CREATE_RENTAL_SUCCESS'
export const CREATE_RENTAL_ERROR = 'CREATE_RENTAL_ERROR'

export const SET_EDIT_RENTAL = 'SET_EDIT_RENTAL'

export const EDIT_RENTAL_BEGIN = 'EDIT_RENTAL_BEGIN'
export const EDIT_RENTAL_SUCCESS = 'EDIT_RENTAL_SUCCESS'
export const EDIT_RENTAL_ERROR = 'EDIT_RENTAL_ERROR'

export const DELETE_RENTAL_BEGIN = 'DELETE_RENTAL_BEGIN'

export const GET_ALLRENTALS_BEGIN = 'GET_ALLRENTALS_BEGIN'
export const GET_ALLRENTALS_SUCCESS = 'GET_ALLRENTALS_SUCCESS'

export const GET_RENTALBYID_BEGIN = 'GET_RENTALBYID_BEGIN'
export const GET_RENTALBYID_SUCCESS = 'GET_RENTALBYID_SUCCESS'
export const GET_RENTALBYID_ERROR = 'GET_RENTALBYID_ERROR'

export const SET_ACTIVE_ACTION = 'SET_ACTIVE_ACTION'
export const SET_ACTIVE_ACTION_SUCCESS = 'SET_ACTIVE_ACTION_SUCCESS'

export const CREATE_ACTION_BEGIN = 'CREATE_ACTION_BEGIN'
export const CREATE_ACTION_SUCCESS = 'CREATE_ACTION_SUCCESS'
export const CREATE_ACTION_ERROR = 'CREATE_ACTION_ERROR'

export const DELETE_ACTION_BEGIN = 'DELETE_ACTION_BEGIN'

export const SET_EDIT_ACTION = 'SET_EDIT_ACTION'

export const EDIT_ACTION_BEGIN = 'EDIT_ACTION_BEGIN'
export const EDIT_ACTION_SUCCESS = 'EDIT_ACTION_SUCCESS'
export const EDIT_ACTION_ERROR = 'EDIT_ACTION_ERROR'

export const CREATE_NOTE_BEGIN = 'CREATE_NOTE_BEGIN'
export const CREATE_NOTE_SUCCESS = 'CREATE_NOTE_SUCCESS'
export const CREATE_NOTE_ERROR = 'CREATE_NOTE_ERROR'

export const SET_ACTIVE_NOTE = 'SET_ACTIVE_NOTE'
export const SET_EDIT_NOTE = 'SET_EDIT_NOTE'

export const EDIT_NOTE_SUCCESS = 'EDIT_NOTE_SUCCESS'
export const EDIT_NOTE_ERROR = 'EDIT_NOTE_ERROR'

export const DELETE_NOTE_BEGIN = 'DELETE_NOTE_BEGIN'

export const CLEAR_FILTERS = 'CLEAR_FILTERS'


